<?php
$GuideFid=array (
  61 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=61\'>设计/策划</A>',
  66 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=66\'>演艺/影视</A>',
  58 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=58\'>技工/一般工人</A>',
  64 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=64\'>经营管理</A>',
  65 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=65\'>保健/美容美发</A>',
  63 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=63\'>金融/财会/出纳</A>',
  67 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=67\'>电子/机械/工程</A>',
  57 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=57\'>客服/文秘/文员</A>',
  59 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=59\'>电脑/网络相关</A>',
  60 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=60\'>旅游/酒店餐饮</A>',
  62 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=62\'>人事/行政/助理</A>',
  68 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=68\'>教育/培训/翻译</A>',
  55 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=55\'>业务/销售/市场</A>',
  56 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=56\'>兼职</A>',
  201 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=201\'>快递/配送/调度员</A>',
  69 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=69\'>房产/建筑/装修</A>',
  183 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=183\'>家居黄页</A>',
  184 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=184\'>理财信贷</A>',
  190 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=190\'>环保网</A>',
  191 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=191\'>服装黄页</A>',
  192 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=192\'>食品黄页</A>',
  193 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=193\'>石油化工</A>',
  194 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=194\'>IT黄页</A>',
  103 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=103\'>快递</A>',
  196 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=196\'>礼品黄页</A>',
  1 => ' -&gt; <A href=\'list.php?fid=1\'>房产</A>',
  108 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=108\'>工商注册/年检</A>',
  197 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=197\'>电子电工</A>',
  105 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=105\'>广告/印刷</A>',
  198 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=198\'>能源冶金</A>',
  182 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A>',
  107 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=107\'>招商加盟</A>',
  118 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A> -&gt; <A href=\'list.php?fid=118\'>职业培训</A>',
  195 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=195\'>印刷包装</A>',
  2 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A>',
  44 => ' -&gt; <A href=\'list.php?fid=9\'>车辆买卖</A> -&gt; <A href=\'list.php?fid=44\'>二手汽车</A>',
  109 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=109\'>会计/审计/评估</A>',
  119 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A> -&gt; <A href=\'list.php?fid=119\'>中小学教育</A>',
  199 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=199\'>农业信息</A>',
  3 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A>',
  12 => ' -&gt; <A href=\'list.php?fid=1\'>房产</A> -&gt; <A href=\'list.php?fid=12\'>二手房</A>',
  47 => ' -&gt; <A href=\'list.php?fid=9\'>车辆买卖</A> -&gt; <A href=\'list.php?fid=47\'>自行车/电动车</A>',
  112 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=112\'>租赁</A>',
  185 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=185\'>影视文化</A>',
  4 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A>',
  11 => ' -&gt; <A href=\'list.php?fid=1\'>房产</A> -&gt; <A href=\'list.php?fid=11\'>房屋出租</A>',
  48 => ' -&gt; <A href=\'list.php?fid=9\'>车辆买卖</A> -&gt; <A href=\'list.php?fid=48\'>摩托车</A>',
  104 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=104\'>网站建设/推广</A>',
  123 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A> -&gt; <A href=\'list.php?fid=123\'>电脑培训</A>',
  186 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=186\'>办公耗材</A>',
  5 => ' -&gt; <A href=\'list.php?fid=5\'>宠物</A>',
  13 => ' -&gt; <A href=\'list.php?fid=1\'>房产</A> -&gt; <A href=\'list.php?fid=13\'>合租房</A>',
  53 => ' -&gt; <A href=\'list.php?fid=9\'>车辆买卖</A> -&gt; <A href=\'list.php?fid=53\'>车辆配件</A>',
  122 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A> -&gt; <A href=\'list.php?fid=122\'>语言培训</A>',
  187 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=187\'>机械</A>',
  6 => ' -&gt; <A href=\'list.php?fid=6\'>同地活动</A>',
  15 => ' -&gt; <A href=\'list.php?fid=1\'>房产</A> -&gt; <A href=\'list.php?fid=15\'>房屋求租</A>',
  116 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=116\'>物流/货运</A>',
  120 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A> -&gt; <A href=\'list.php?fid=120\'>管理/MBA培训</A>',
  188 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=188\'>装修建材</A>',
  7 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A>',
  17 => ' -&gt; <A href=\'list.php?fid=1\'>房产</A> -&gt; <A href=\'list.php?fid=17\'>商铺</A>',
  52 => ' -&gt; <A href=\'list.php?fid=9\'>车辆买卖</A> -&gt; <A href=\'list.php?fid=52\'>汽修/保养/装饰</A>',
  110 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=110\'>担保/保险/投资</A>',
  126 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A> -&gt; <A href=\'list.php?fid=126\'>文艺|体育培训</A>',
  8 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A>',
  19 => ' -&gt; <A href=\'list.php?fid=1\'>房产</A> -&gt; <A href=\'list.php?fid=19\'>写字楼</A>',
  46 => ' -&gt; <A href=\'list.php?fid=9\'>车辆买卖</A> -&gt; <A href=\'list.php?fid=46\'>司机求职</A>',
  106 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=106\'>喷绘招牌</A>',
  125 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A> -&gt; <A href=\'list.php?fid=125\'>学前教育</A>',
  9 => ' -&gt; <A href=\'list.php?fid=9\'>车辆买卖</A>',
  20 => ' -&gt; <A href=\'list.php?fid=1\'>房产</A> -&gt; <A href=\'list.php?fid=20\'>厂房/仓库</A>',
  50 => ' -&gt; <A href=\'list.php?fid=9\'>车辆买卖</A> -&gt; <A href=\'list.php?fid=50\'>驾校/陪练</A>',
  113 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=113\'>翻译/速记</A>',
  124 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A> -&gt; <A href=\'list.php?fid=124\'>学历教育</A>',
  189 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=189\'>玩具黄页</A>',
  10 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A>',
  14 => ' -&gt; <A href=\'list.php?fid=1\'>房产</A> -&gt; <A href=\'list.php?fid=14\'>日租房/短租房</A>',
  45 => ' -&gt; <A href=\'list.php?fid=9\'>车辆买卖</A> -&gt; <A href=\'list.php?fid=45\'>租车</A>',
  49 => ' -&gt; <A href=\'list.php?fid=9\'>车辆买卖</A> -&gt; <A href=\'list.php?fid=49\'>拼车/顺风车</A>',
  70 => ' -&gt; <A href=\'list.php?fid=3\'>企业招聘</A> -&gt; <A href=\'list.php?fid=70\'>其他职位</A>',
  111 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=111\'>法律咨询</A>',
  114 => ' -&gt; <A href=\'list.php?fid=8\'>商务服务</A> -&gt; <A href=\'list.php?fid=114\'>办公设备维修</A>',
  121 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A> -&gt; <A href=\'list.php?fid=121\'>出国留学</A>',
  200 => ' -&gt; <A href=\'list.php?fid=182\'>企业黄页</A> -&gt; <A href=\'list.php?fid=200\'>其它黄页</A>',
  24 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=24\'>二手台式电脑</A>',
  25 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=25\'>二手笔记本</A>',
  26 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=26\'>手机/通讯相关</A>',
  27 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=27\'>数码/影音</A>',
  28 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=28\'>音响/摄录</A>',
  29 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=29\'>软件/图书/音像</A>',
  30 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=30\'>艺术/工艺/收藏品</A>',
  31 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=31\'>母婴/儿童用品</A>',
  32 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=32\'>服饰/箱包/鞋帽</A>',
  33 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=33\'>化妆品/保健品</A>',
  36 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=36\'>办公用品/耗材</A>',
  37 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=37\'>运动/健身器材</A>',
  38 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=38\'>家居/日用百货</A>',
  40 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=40\'>二手家电</A>',
  42 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=42\'>网游/装备/虚拟物品</A>',
  43 => ' -&gt; <A href=\'list.php?fid=2\'>跳蚤市场</A> -&gt; <A href=\'list.php?fid=43\'>其他物品</A>',
  71 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=71\'>家政</A>',
  72 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=72\'>保洁</A>',
  73 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=73\'>搬家</A>',
  74 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=74\'>装修/装饰</A>',
  75 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=75\'>管道疏通/打孔</A>',
  79 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=79\'>礼仪婚庆/摄影</A>',
  81 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=81\'>养身/保健</A>',
  83 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=83\'>旅游/洒店/签证</A>',
  85 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=85\'>送水/送气/送花</A>',
  87 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=87\'>市场/营销</A>',
  88 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=88\'>求兼职</A>',
  89 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=89\'>文秘/文员</A>',
  90 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=90\'>技工/一般工人</A>',
  91 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=91\'>电脑/网络相关</A>',
  92 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=92\'>旅游/酒店餐饮</A>',
  93 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=93\'>设计/策划</A>',
  94 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=94\'>行政/助理</A>',
  95 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=95\'>金融/财会/出纳</A>',
  96 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=96\'>经营管理</A>',
  97 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=97\'>保健/美容美发</A>',
  98 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=98\'>音乐/表演/主持</A>',
  99 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=99\'>电子/机械/工程</A>',
  100 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=100\'>写作/翻译</A>',
  101 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=101\'>政府/事业单位</A>',
  102 => ' -&gt; <A href=\'list.php?fid=4\'>求职简历</A> -&gt; <A href=\'list.php?fid=102\'>其他职位</A>',
  127 => ' -&gt; <A href=\'list.php?fid=10\'>教育培训</A> -&gt; <A href=\'list.php?fid=127\'>其他培训</A>',
  128 => ' -&gt; <A href=\'list.php?fid=5\'>宠物</A> -&gt; <A href=\'list.php?fid=128\'>宠物狗</A>',
  129 => ' -&gt; <A href=\'list.php?fid=5\'>宠物</A> -&gt; <A href=\'list.php?fid=129\'>宠物猫</A>',
  130 => ' -&gt; <A href=\'list.php?fid=5\'>宠物</A> -&gt; <A href=\'list.php?fid=130\'>宠物用品</A>',
  131 => ' -&gt; <A href=\'list.php?fid=5\'>宠物</A> -&gt; <A href=\'list.php?fid=131\'>宠物店/服务</A>',
  132 => ' -&gt; <A href=\'list.php?fid=5\'>宠物</A> -&gt; <A href=\'list.php?fid=132\'>宠物领养/赠送</A>',
  138 => ' -&gt; <A href=\'list.php?fid=6\'>同地活动</A> -&gt; <A href=\'list.php?fid=138\'>活动召集</A>',
  139 => ' -&gt; <A href=\'list.php?fid=6\'>同地活动</A> -&gt; <A href=\'list.php?fid=139\'>团购/打折</A>',
  140 => ' -&gt; <A href=\'list.php?fid=6\'>同地活动</A> -&gt; <A href=\'list.php?fid=140\'>结伴出游</A>',
  142 => ' -&gt; <A href=\'list.php?fid=6\'>同地活动</A> -&gt; <A href=\'list.php?fid=142\'>公益活动/志愿者</A>',
  143 => ' -&gt; <A href=\'list.php?fid=6\'>同地活动</A> -&gt; <A href=\'list.php?fid=143\'>讲座/研讨会/招聘会</A>',
  144 => ' -&gt; <A href=\'list.php?fid=6\'>同地活动</A> -&gt; <A href=\'list.php?fid=144\'>交友征婚</A>',
  180 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=180\'>家居维修</A>',
  181 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=181\'>电脑服务</A>',
  175 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=175\'>餐饮美食</A>',
  176 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=176\'>休闲娱乐</A>',
  178 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=178\'>家电维修</A>',
  179 => ' -&gt; <A href=\'list.php?fid=7\'>生活服务</A> -&gt; <A href=\'list.php?fid=179\'>医疗</A>',
);?>