<?php
$webdb['yzImgComment']='0';
$webdb['flashtime']='0';
$webdb['showComment']='1';
$webdb['forbidComment']='0';
$webdb['showCommentRows']='8';
$webdb['viewNoPassGuestBook']='1';
$webdb['yzImgContribute']='0';
$webdb['groupPassContribute']='3';
$webdb['regmoney']='5';
$webdb['MaxOnlineUser']='1000';
$webdb['groupPassShopYz']='3,4';
$webdb['groupPassPassGuestBook']='3';
$webdb['ifOpenGuestBook']='1';
$webdb['yzImgGuestBook']='1';
$webdb['ContributeFid']='2';
$webdb['SPbencandy_filename']='html/5special{$fid}/show{$id}.htm';
$webdb['groupPassLogYz']='3,4';
$webdb['RegYz']='1';
$webdb['FtpPort']='21';
$webdb['PostSortStep']='2';
$webdb['ListSonline']='2';
$webdb['_Notice']='29weSgiaHR0cDovL3d3dy5waHAxNjguY29tL05vdGljZS8/dXJsPSR3ZWJkYlt3d3dfdXJsXSIsUEhQMTY4X1BBVEguImNhY2hlL05vdGljZS5waHAiKTs=';
$webdb['CommentTime']='5';
$webdb['JsListRows']='5';
$webdb['JsListLeng']='36';
$webdb['ListSonRows']='9';
$webdb['ListSonLeng']='34';
$webdb['weburl']='/';
$webdb['MailType']='smtp';
$webdb['allowMemberCommentPass']='1';
$webdb['Listsortnameline']='2';
$webdb['AvoidGatherPre']='';
$webdb['AvoidCopy']='0';
$webdb['AvoidGather']='0';
$webdb['AvoidSave']='0';
$webdb['AvoidGatherString']='';
$webdb['is_waterimg']='0';
$webdb['adminPostEditType']='html';
$webdb['article_show_step']='2';
$webdb['ifContribute']='1';
$webdb['allowGuestSearch']='0';
$webdb['DefaultIndexHtml']='0';
$webdb['kill_badword']='0';
$webdb['KeepTodayCount']='0';
$webdb['close_count']='1';
$webdb['ShowKeywordColor']='#F70968';
$webdb['ifShowKeyword']='1';
$webdb['UseFtp']='0';
$webdb['FtpDir']='111';
$webdb['FtpWeb']='';
$webdb['FtpPwd']='admin';
$webdb['FtpName']='admin';
$webdb['passport_type']='';
$webdb['ListLeng']='70';
$webdb['showsortlogo']='0';
$webdb['emailOnly']='1';
$webdb['allowGuestCommentPass']='1';
$webdb['ShowMenu']='0';
$webdb['GuestBookNum']='8';
$webdb['ShopOtherSend']='18';
$webdb['ShopNormalSend']='8';
$webdb['ShopEmsSend']='25';
$webdb['groupUpType']='0';
$webdb['groupTime']='180';
$webdb['SideTitleStyle']='side_tpl/2';
$webdb['list_filename2']='list.php?fid-{$fid}-page-{$page}.htm';
$webdb['SPlist_filename']='html/4special{$fid}/list{$page}.htm';
$webdb['waterimg']='images/default/water.gif';
$webdb['guide_word']='房产租赁|list.php?fid=1|0||55
物品交易|list.php?fid=2|0||56
个人求职|list.php?fid=4|0||57
企业招聘|list.php?fid=3|0||58
同城活动|list.php?fid=6|0||60';
$webdb['HideNopowerPost']='1';
$webdb['listPicRows']='5';
$webdb['SideSortStyle']='side_sort/2';
$webdb['labelsort_show_step']='0';
$webdb['CommentOrderType']='0';
$webdb['showNoPassComment']='0';
$webdb['allowGuestComment']='1';
$webdb['TheSameMakeIndexHtml']='0';
$webdb['ArticleHeart']='欠扁|1.gif
支持|2.gif
很棒|3.gif
找骂|4.gif
搞笑|5.gif
软文|6.gif
不解|7.gif
吃惊|8.gif';
$webdb['heart_time']='30';
$webdb['heart_noRecord']='1';
$webdb['UseArticleHeart']='1';
$webdb['ForceDel']='0';
$webdb['propagandize_jumpto']='/';
$webdb['propagandize_LogDay']='5';
$webdb['propagandize_close']='0';
$webdb['propagandize_Money']='2';
$webdb['AutoTitleNum']='1';
$webdb['YZ_IdcardMoney']='20';
$webdb['EditYzEmail']='0';
$webdb['EditYzMob']='0';
$webdb['EditYzIdcard']='0';
$webdb['YZ_EmailMoney']='10';
$webdb['YZ_MobMoney']='15';
$webdb['MailServer']='smtp.vip.163.com';
$webdb['sms_wi_id']='90';
$webdb['sms_wi_pwd']='30';
$webdb['bencandy_filename2']='bencandy.php?fid-{$fid}-id-{$id}-page-{$page}.htm';
$webdb['SPlist_filename2']='listsp.php?fid-{$fid}-page-{$page}.htm';
$webdb['ForbidIp']='';
$webdb['AdminIp']='';
$webdb['AllowVisitIp']='';
$webdb['BbsUserAutoPass']='1';
$webdb['forbidReg']='0';
$webdb['ForbidCountDomain']='';
$webdb['Reg_Field']='a:1:{s:8:\\\\\\\\\\\\\\\\\\\\\\\"field_db\\\\\\\\\\\\\\\\\\\\\\\";N;}';
$webdb['waterAlpha']='80';
$webdb['passport_TogetherLogin']='1';
$webdb['deleteArticleMoney']='-1';
$webdb['postArticleMoney']='1';
$webdb['comArticleMoney']='3';
$webdb['hotArticleNum']='100';
$webdb['newArticleTime']='24';
$webdb['ListShowIcon']='0';
$webdb['autoGetKeyword']='1';
$webdb['MoneyRatio']='100';
$webdb['yeepay_id']='1210215301';
$webdb['yeepay_key']='ve4ets3huzxruch0tsf6nga7a2lpckm8h9p7qnefj31q49ms8bhl3qin6q0g';
$webdb['forbidRegName']='';
$webdb['list_cache_time']='5';
$webdb['index_cache_time']='5';
$webdb['autoGetSmallPic']='1';
$webdb['autoCutSmallPic']='1';
$webdb['ForbidRepeatTitle']='1';
$webdb['viewNoPassArticle']='0';
$webdb['ArticleDownloadUseFtp']='0';
$webdb['ArticleDownloadDirTime']='0';
$webdb['ArticlePicWidth']='800';
$webdb['ArticlePicHeight']='600';
$webdb['SortUseOtherModule']='1';
$webdb['ForbidShowPhpPage']='0';
$webdb['SPbencandy_filename2']='showsp.php?fid-{$fid}-id-{$id}-page-{$page}.htm';
$webdb['list_filename']='html/{$fid}/{$page}.htm';
$webdb['bencandy_filename']='html/{$fid}-{$dirid}/{$id}-{$page}.htm';
$webdb['showsp_cache_time']='5';
$webdb['PostNotice']='<font face=SimSun>
<p><font face=SimSun>2、如果是转载内容，请务必填写稿件来源网址及出处。<br />3、所引起的版权纠纷与法律责任由发布者承担。</font></p></font>';
$webdb['allowDownMv']='0';
$webdb['autoPlayFirstMv']='1';
$webdb['XunLei_ID']='08311';
$webdb['FlashGet_ID']='6370';
$webdb['passport_path']='bbs';
$webdb['FtpHost']='127.0.0.1';
$webdb['NewsMakeHtml']='0';
$webdb['MakeIndexHtmlTime']='0';
$webdb['bencandy_cache_time']='5';
$webdb['passport_pre']='pw_';
$webdb['rand_num']='1345688617';
$webdb['UseMoneyType']='cms';
$webdb['webmail']='admin@admin.com';
$webdb['hideFid']='';
$webdb['web_open']='1';
$webdb['close_why']='网站维护当中,
暂停访问.';
$webdb['style']='default';
$webdb['yzimg_letter_num']='';
$webdb['yzimg_letter_differen']='0';
$webdb['yzimg_simple']='0';
$webdb['label_cache_time']='0';
$webdb['DownLoad_readfile']='1';
$webdb['AutoCutFace']='1';
$webdb['yzImgAdminLogin']='1';
$webdb['memberNotice']='欢迎大家勇跃投稿,投稿可得积分奖励!!';
$webdb['AutoPassCompany']='1';
$webdb['description']='整站系统';
$webdb['passport_url']='http://192.168.18.106/or58/bbs';
$webdb['cache_time_new']='5';
$webdb['cache_time_hot']='5';
$webdb['cache_time_com']='5';
$webdb['cache_time_like']='5';
$webdb['cache_time_pic']='5';
$webdb['metakeywords']='php168 news bbs board php mysql forums';
$webdb['Del_MoreUpfile']='1';
$webdb['webname']='PHP168整站系统';
$webdb['sitehash']='11UVABWgNXAwVbBANTVAQBBQEDAFZRAQ9cUFNXBAoCAgY';
$webdb['siteid']='a57ba41c323b41c0';
$webdb['siteownerid']='11ddaaad78bae02840';
$webdb['alipay_scale']='10';
$webdb['tenpay_id']='1210215301';
$webdb['sms_type']='winic';
$webdb['sms_es_name']='10';
$webdb['sms_es_key']='20';
$webdb['SystemType']='f';
$webdb['miibeian_gov_cn']='蜀ICP备11003268号';
$webdb['copyright']='Copyright @2011 同地网版权所有 ';
$webdb['mymd5']='55714495';
$webdb['companyTrade']='机械及行业设备
普通机械制造
通用零部件
五金配件
金属工具
电动工具
电子元件
电子器件
照明及照明器具
安全防护设备
包装
造纸及纸制品
电机、电工电器
电工器材
通用仪器仪表
专用仪器仪表
交通运输设备、零部件
办公、文教用品
数码、电脑及网络配件
日常家居用品
木材、木制品
家具
家用电器
礼品、工艺美术品
食品、饮料
通信产品
玩具
印刷设备
运动、休闲、保健用品
鞋、帽
服装
日用化学品
农用化学品
胶粘剂
染料、颜料、涂料和油墨
催化剂和助剂
库存精细化学品
食品和饲料添加剂
塑料
橡胶制品
环保、环保设备
建筑、建材
能源
粮油、农制品
金属
医药、保健及医疗设备
纺织
皮革
煤焦化产品
日常服务
广告服务
教育培训
认证
创意设计
物流服务
进出口代理
维修及安装服务
广告、展览器材
专业录音、放音设备
光学摄影器材
编辑制作设备
播出、前端设备
建筑、装饰业
房地产
安装工程
邮电通信
事务所、公证
卫生、体育、社会、福利
公共服务业
金融、保险
实业公司、商业贸易
高新技术开发区
卡类市场';
$webdb['bokecc_id']='';
$webdb['rand_num_inputname']='fz';
$webdb['yzImgReg']='0';
$webdb['limitRegTime']='';
$webdb['forbidRegIp']='';
$webdb['cookieDomain']='';
$webdb['RegCompany']='0';
$webdb['pay99_key']='';
$webdb['forbid_show_bug']='1';
$webdb['mirror']='';
$webdb['updir']='upload_files';
$webdb['upfileType']='.rar .txt .jpg .gif .bmp .png .zip .mp3 .wma .wmv .mpeg .mpg .rm .ram .htm .doc .swf .avi .flv .sql .doc .ppt .xls .chm .pdf';
$webdb['upfileMaxSize']='';
$webdb['totalSpace']='100';
$webdb['time']='0';
$webdb['admin_url']='or58login';
$webdb['www_url']='http://www.85yp.com';
$webdb['MoneyDW']='个';
$webdb['MoneyName']='整站积分';
$webdb['UserEmailAutoPass']='1';
$webdb['cnzz_id']='1380703824';
$webdb['cnzz_pwd']='88544993330';
$webdb['cnzz_open']='1';
$webdb['tenpay_key']='cdc2627881c7f97dc4416dd25a19b485';
$webdb['alipay_id']='test@test.com';
$webdb['alipay_key']='';
$webdb['alipay_partner']='';
$webdb['alipay_service']='create_partner_trade_by_buyer';
$webdb['alipay_transport']='https';
$webdb['pay99_id']='';
$webdb['Money2card']='0';
$webdb['MailPort']='25';
$webdb['MailId']='or58@vip.163.com';
$webdb['MailPw']='t19851024123456';
$webdb['waterpos']='9';
$webdb['if_gdimg']='0';
$webdb['BuySpacesizeMoney']='50';
